### ISSUE TITLE
Allow cut/paste of QR image

### ISSUE THREAD

**Issue by jiqiren** [mshibanami/QRCodeGen#1]
I need to put the QR image into documents (like in pages).

I was hoping I could just copy the image and then paste. As of now - I have to screenshot the QR code then drag it Pages/Word/etc to add the QR image.

Please add this feature request.

PS. I'm a paying customer. 😎

**Comment by mshibanami** [comment]
Thanks for your suggestion, @jiqiren. I agree that it would be a useful feature. I think I'll release a new version for it by the end of  this month.

PS. Thanks for buying. 🙏

**Comment by mshibanami** [comment]
Hi @jiqiren, Sorry to have kept you waiting. 

New version v1.1 including this feature is available now. Would you please try it? FYI, it works like this: https://www.youtube.com/watch?v=OrwaJQl-WDg

I'll close this issue. Thanks so much for your feature request! If you have a question, please feel free to reopen this issue.
